export enum Roles {
    DOCTOR,
    NURSE,
    CAREGIVER,
    PHARMACIST,
    DIETICIAN,
    PHYSIOTHERAPIST,
    PSYCHOLOGIST,
    ADMINISTRATOR,
    RECEPTIONIST,
    LAB_TECHNICIAN,
    AMBULANCE_DRIVER,
    HOME_HEALTH_AIDE,
    SOCIAL_WORKER,
    OTHER
}